export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'new': 'New',
    'cancel': 'Cancel',
    'save': 'Save',
    'back': 'Back',
    'filter': 'Filter',
    'actions': 'Actions',
    'edit': 'Update',
    'yes': 'Yes',
    'no': 'No',
    'ok': 'Ok',
    'delete': 'Delete',
    'delete_question': 'Do you want to delete this record?',
    'cancel_question': 'Do you want to cancel this action?',
    'save_question': 'Do you want to save this record?',
    'dialog_title': 'KPI',
    'large': 'Large',
    'medium': 'Medium',
    'small': 'Small',

    'year': 'Year',
    'month': 'Month',

    'date': 'Date',
    'region': 'Region',
    'country': 'Country',
    'headquarter': 'Headquarter',
    'distributor': 'Distributor',

    'headquarter_master_maintainance': 'Headquarter Master Maintenance',
    'headquarter_name': 'Headquarter Name',

    'tradingcompany_master_maintainance': 'Trading Company Master Maintainance',
    'tradingcompany_name': 'Trading Company Name',

    'region_master_maintainance': 'Region Master Maintainance',
    'region_code': 'Region Code',
    'region_name': 'Region Name',

    'country_master_maintainance': 'Country Master Maintainance',
    'region_id': 'Region ID',
    'country_name': 'Country Name',

    'authority_master_maintainance': 'Authority Master Maintainance',
    'authority_name': 'Authority Name',
    'authority_detail': 'Authority Detail',

    'user_mst_master_maintainance': 'User Master Maintainance',
    'dist_id': 'DIST ID',
    'login_name': 'Login Name',
    'login_id': 'Login ID',
    'password': 'Password',
    'username': 'Username',
    'position': 'Position',
    'permission': 'Permission',
    'authority_id': 'Authority ID',

    'distributor_master_maintainance': 'Distributor Master Maintainance',
    'dist_name': 'DIST Name',
    'country_id': 'Country ID',
    'headquarter_id': 'Headquarter ID',
    'trading_company_id': 'Trading Company ID',
    'trading_company': 'Trading Company',
    'administration_company': 'Administration Company',
    'dist_code': 'DIST Code',
    'distributor_name': 'Distributor Name',
    'db': 'DB',
    'non_db': 'Non DB',
    'db_flg': 'DB / Non DB',
    'dist_disclosure_flag': 'Data Open',
    'flag_1': 'Flag 1',
    'flag_2': 'Flag 2',
    'flag_3': 'Flag 3',
    'flag_4': 'Flag 4',
    'flag_5': 'Flag 5',

    'dealer_master_maintainance': 'Dealer Master Maintainance',
    'dlr_name': 'DLR Name',
    'dlr_code': 'DLR Code',
    'vehicle_sales_vol': 'Vehicle Sales Volume',
    'zone': 'Zone',
    'zone_code': 'Zone Code',
    'zone_name': 'Zone Name',
    'district': 'District',
    'district_code': 'District Code',
    'district_name': 'District Name',
    'dlr_group': 'DLR Group',
    'dlr_group_code': 'DLR Group Code',
    'dlr_group_name': 'DLR Group Name',
    'attr_1_1': 'Attr 1_1',
    'attr_1_2': 'Attr 1_2',
    'attr_1_3': 'Attr 1_3',
    'attr_2_1': 'Attr 2_1',
    'attr_2_2': 'Attr 2_2',
    'attr_2_3': 'Attr 2_3',
    'attr_3_1': 'Attr 3_1',
    'attr_3_2': 'Attr 3_2',
    'attr_3_3': 'Attr 3_3',
    'attr_4_1': 'Attr 4_1',
    'attr_4_2': 'Attr 4_2',
    'attr_4_3': 'Attr 4_3',
    'attr_5_1': 'Attr 5_1',
    'attr_5_2': 'Attr 5_2',
    'attr_5_3': 'Attr 5_3',

    'carmodel_master_maintainance': 'Car Model Master Maintainance',
    'vin_code': 'VIN Code',
    'model_name': 'Model Name',
    'model_code': 'Model Code',
    'wmi': 'WMI',
    'vds': 'VDS',

    'supply_master_maintainance': 'Supply Master Maintainance',
    'supply_code': 'Supply Code',
    'supply_category_code': 'Supply Category Code',
    'supply_detail': 'Supply Detail',
  
    

    'supplysales_master_maintainance': 'Supply Sales Master Maintainance',
    'sales_code': 'Sales Code',
    'dlr_id': 'Dealer ID',
    'invoice_no': 'Invoice Number',
    'sales_staff_code': 'Sales Staff Code',
    'vehicle_sales_code': 'Vehicle Sales Code',
    'supply_name': 'Supply Name',
    'sales_amount': 'Sales Amount',
    'sales_datetime': 'Sales DateTime',
    'genuine_flag': 'Genuine Flag',
    'package_flag': 'Package Flag',

    'processrequirement_master_maintainance': 'Process Requirements Master Maintainance',

    'evaluations_1': 'Evaluations 1',
    'evaluations_2': 'Evaluations 2',
    'evaluations_3': 'Evaluations 3',
    'evaluations_4': 'Evaluations 4',
    'evaluations_5': 'Evaluations 5',
    'evaluations_6': 'Evaluations 6',
    'evaluations_7': 'Evaluations 7',
    'evaluations_8': 'Evaluations 8',
    'evaluations_9': 'Evaluations 9',




    'menu_administration_header' : 'Administration Menu',
    'menu_company' : 'Headquarter Master Maintenance',
    'menu_trading' : 'Trading Company Master Maintenance',
    'menu_dist' : 'DIST Master Maintenance',
    'menu_dlr' : 'DLR Master Maintenance',
    'menu_accessory' : 'Accessory Master Maintenance',
    'menu_vehicle' : 'Vehicle Model Master Maintenance',
    'menu_user' : 'User Master Maintenance',
    'menu_sales' : 'Accessory Sales Data Master Maintenance',
    'menu_process' : 'Process Requirement Data Master Maintenance',

    'data_master_maintainance': 'KPI Data Master Maintainance',


    'header_accessory_sales_data_upload' : 'Accessory Sales Data Upload',
    'header_sales_kpi_data' : 'Sales KPI Data',
    'header_free_kpi_data' : 'Free KPI Data',
    'header_process_kpi_input' : 'Process KPI Data',
    'data_format_download' : 'Data Format Download (Excel)',


    'all_trading_companies': 'All Trading Companies',
    'all_dealers': 'All Dealers',
    'all_distributors': 'All Distributors',
    'all_regions': 'All Regions',
    'all_countries': 'All Countries',
    'project_title': 'SALES KPI Management System',
    'loading': 'Loading...',
    'dealer': 'Dealer',

    'all_headquarters': 'All Headquarters',

    'all_dbs': 'All DBs',
    'db1': 'DB1',
    'db2': 'DB2',
    'db3': 'DB3',
    'db4': 'DB4',
    'db5': 'DB5',
    'db6': 'DB6',
    'db7': 'DB7',
    'db8': 'DB8',
    

    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December',


    'col_5_accessory_sales' : 'Accessory Sales',
    'col_5_sales_unit' : 'Sales Unit',
    'col_5_process_requirement' : 'Process Requirement',

    'col_6_sales_code' : 'Sales Code',
    'col_6_carmodel' : 'CarModel',
    'col_6_item_category' : 'Item Category',
    'col_6_sales_classification' : 'Sales Classification',
    'col_6_vehicle_sales' : 'Vehicle Sales',
    'col_6_gen_non_gen' : 'Genuine/Non-Genuine',
    'col_6_unit_package' : 'Unit/Package',
    'col_6_item_no' : 'ItemNo.',
    'col_6_sales_unit' : 'Sales Unit',
    'col_6_process_requirement' : 'Process Requirement',


    'btn_search' : 'Search',
    'process_kpi_input' : 'Process KPI Input',
    'register': 'Register',


    'process_requirement_title_master': 'Process Requirement Title Master',
    'english': 'English',
    'localized': 'Localized',
    'evaluation_item_1': 'Evaluation Item 1',
    'evaluation_item_2': 'Evaluation Item 2',
    'evaluation_item_3': 'Evaluation Item 3',
    'evaluation_item_4': 'Evaluation Item 4',
    'evaluation_item_5': 'Evaluation Item 5',
    'evaluation_item_6': 'Evaluation Item 6',
    'evaluation_item_7': 'Evaluation Item 7',
    'evaluation_item_8': 'Evaluation Item 8',
    'need_improvement': '0: Need improvement',
    'minimum': '1: Minimum',
    'good': '2: Good',
    'ideal_situation': '3: Ideal Situation',


    'access_blocked': 'You do not have privilege to access this page',
    'access_heading' : 'Access Blocked!',

    'uploading_file' : 'UPLOADING....Please wait...',
    'whats_new' : 'What\'s New',
    'information' : 'Information',


    'new_car': 'New Car',
    'sold_car': 'Sold Car',
    'old_car': 'Old Car',
    'retail': 'Retail',
    'fleet': 'Fleet',
    'item_code': 'Item Code',
    'genuine': 'Gennuine',
    'non_genuine': 'Non-Genuine',
    'unit': 'Unit',
    'package': 'Package',

    'sales_category': 'Sales Category',
    'item_name': 'Item Name',
    'sales': 'Sales',
};